### PR TITLE
Create subscription abstraction for file and live subscription

### PR DESCRIPTION
**Pull request by xiongtx**

### CODE REVIEW

**Review by twashing — CHANGES_REQUESTED** [review]
Code hygiene looks really good. 

Mmm, trying to pull in the an [existing file](https://github.com/twashing/ibgateway/blob/protocolize-requests/workbench/clojure/com/interrupt/ibgateway/core.clj#L72-L96), gives me this error.

```
Exception in thread "async-dispatch-5" java.lang.IllegalArgumentException: No matching clause:
        at com.interrupt.ibgateway.component.switchboard$kickoff_stream_workbench$fn__57898$state_machine__13639__auto____57907$fn__57909.invoke(switchboard.clj:1276)
        at com.interrupt.ibgateway.component.switchboard$kickoff_stream_workbench$fn__57898$state_machine__13639__auto____57907.invoke(switchboard.clj:1276)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at clojure.core.async.impl.ioc_macros$take_BANG_$fn__13657.invoke(ioc_macros.clj:986)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__8608$fn__8609.invoke(channels.clj:95)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

I think this is because the `case` [statement](https://github.com/twashing/ibgateway/blob/281f0c2cbe8e6150f7030102783e7ab430a3429b/src/clojure/com/interrupt/ibgateway/component/switchboard.clj#L1276) is getting a non-matching clause. I tried putting in a default case, but no dice. Are you getting the same thing?

**Comment by xiongtx** [comment]
Hmm, I tried w/ a small sample file and it works fine:

```clojure
{:topic :tick-size, :ticker-id 0, :field 5, :size 54}
{:topic :tick-string, :ticker-id 0, :tick-type 45, :value "1534781292"}
{:topic :tick-price, :ticker-id 0, :field 4, :price 300.81, :can-auto-execute 0}
```

Try adding a `println` for the value before the `case` to see what's triggering the issue.

**Comment by twashing** [comment]
Did you try with `live-recordings/2018-08-20-TSLA.edn` or `live-recordings/2018-08-27-TSLA.edn`? When printing out the topic, I get:
```
topic:  nil
```

Also, when running `com.interrupt.edgar.subscription-test`, I get: 
```
Exception in thread "async-dispatch-1" java.lang.RuntimeException: EOF while reading
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.EdnReader.read(EdnReader.java:130)
        at clojure.lang.EdnReader.read(EdnReader.java:111)
        at clojure.edn$read.invokeStatic(edn.clj:35)
        at clojure.edn$read.invokeStatic(edn.clj:14)
        at clojure.edn$read.invoke(edn.clj:14)
        at com.interrupt.edgar.subscription.FileSubscription$fn__14911$state_machine__10941__auto____14926$fn__14930.invoke(subscription.clj:14)
        at com.interrupt.edgar.subscription.FileSubscription$fn__14911$state_machine__10941__auto____14926.invoke(subscription.clj:14)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at com.interrupt.edgar.subscription.FileSubscription$fn__14911.invoke(subscription.clj:14)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by xiongtx** [comment]
Can you try restarting the REPL? I'm not getting these errors.

**Comment by twashing** [comment]
Yep. I definitely restart, even with a `lein do clean, cljsbuild auto` in one window. Then a `lein repl`, in another.  It's happening repeatably on my system. 

Anyways, we can tackle it tomorrow evening.

**Comment by xiongtx** [comment]
I think function calls like [`(.tickString wrapper %1 %2 %3)`](https://github.com/twashing/ibgateway/pull/19/files#diff-01acfbf05bbdde00d03af0a661937c9cL1306) are being applying to `(vals ...)`, but the vals are not guaranteed to be in a particular order. That seems wrong.

**Review by twashing — APPROVED** [review]

**Pull request merged**
